import { Check, ChevronRight, ClipboardCheck, Clock3, Printer, Search, ShieldCheck, Stethoscope, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { PageHeader } from '../components/ui';
import { clinicalSkills } from '../content/clinicalSkills';

export default function ClinicalSkillsPage() {
  const [params, setParams] = useSearchParams();
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All skills');
  const [checked, setChecked] = useState<number[]>([]);
  const categories = [...new Set(clinicalSkills.map((skill) => skill.category))];
  const filtered = useMemo(() => clinicalSkills.filter((skill) => (category === 'All skills' || skill.category === category) && `${skill.title} ${skill.category} ${skill.steps.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  const selected = clinicalSkills.find((skill) => skill.id === params.get('skill'));
  const open = (id: string) => { const next = new URLSearchParams(params); next.set('skill', id); setParams(next); setChecked([]); };
  const close = () => { const next = new URLSearchParams(params); next.delete('skill'); setParams(next); setChecked([]); };

  return <div><PageHeader eyebrow="CLINICAL SKILLS CENTER" title="Practice the sequence. Understand the safety." description="Use these visual checkoff guides to prepare—but perform every skill exactly as your school, instructor, facility, law, and product instructions require." />
    <section className="library-toolbar"><label className="field field--search"><Search /><span className="sr-only">Search skills</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search a clinical skill" /></label><div className="segmented-control segmented-control--wrap">{['All skills', ...categories].map((item) => <button key={item} className={category === item ? 'is-active' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div></section>
    <div className="skill-grid">{filtered.map((skill, index) => <button className="skill-card" key={skill.id} onClick={() => open(skill.id)}><div className="skill-card__visual"><span>{String(index + 1).padStart(2, '0')}</span><Stethoscope /></div><div><span className="eyebrow">{skill.category}</span><h2>{skill.title}</h2><p>{skill.steps.slice(0, 2).join(' ')}</p><div><span><Clock3 /> {skill.minutes} min</span><span><ClipboardCheck /> {skill.steps.length} steps</span></div><strong>Open guide <ChevronRight /></strong></div></button>)}</div>
    <section className="scope-banner"><ShieldCheck /><div><strong>Skills safety is local.</strong><p>These guides support recall. They do not authorize a procedure or replace competency validation, orders, manufacturer instructions, scope rules, or facility policy.</p></div></section>
    {selected && <div className="dialog-backdrop dialog-backdrop--page" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><article className="skill-detail" role="dialog" aria-modal="true" aria-label={`${selected.title} skill guide`}><header><div><span className="eyebrow">{selected.category} · SKILLS CHECKOFF</span><h1>{selected.title}</h1><p>Check each step as you rehearse. Reloading clears this temporary checklist.</p></div><button className="icon-button" onClick={close} aria-label="Close guide"><X /></button></header><div className="skill-detail__toolbar"><span><Clock3 /> About {selected.minutes} minutes</span><button className="button button--secondary" onClick={() => window.print()}><Printer /> Print checklist</button></div><section><h2>Supplies</h2><div className="supply-list">{selected.supplies.map((item) => <span key={item}>{item}</span>)}</div></section><section><h2>Prepare</h2><ol className="number-list">{selected.preparation.map((item) => <li key={item}>{item}</li>)}</ol></section><section><h2>Procedure steps</h2><div className="checkoff-list">{selected.steps.map((step, index) => <button key={step} className={checked.includes(index) ? 'is-checked' : ''} onClick={() => setChecked((values) => values.includes(index) ? values.filter((item) => item !== index) : [...values, index])}><span>{checked.includes(index) ? <Check /> : index + 1}</span><p>{step}</p></button>)}</div></section><div className="detail-grid"><section><h2>Safety checkpoints</h2><ul className="check-list">{selected.safetyCheckpoints.map((item) => <li key={item}><ShieldCheck />{item}</li>)}</ul></section><section><h2>Common mistakes</h2><ul>{selected.commonMistakes.map((item) => <li key={item}>{item}</li>)}</ul></section></div><section className="documentation-example"><span className="eyebrow">DOCUMENTATION EXAMPLE</span><blockquote>{selected.documentationExample}</blockquote></section><section><h2>Patient teaching</h2><ul className="check-list">{selected.patientTeaching.map((item) => <li key={item}><Check />{item}</li>)}</ul></section><footer><span>{checked.length} of {selected.steps.length} steps rehearsed</span><div className="meter__track"><span style={{ width: `${(checked.length / selected.steps.length) * 100}%` }} /></div><a href={selected.source.url} target="_blank" rel="noreferrer">Reference: {selected.source.organization}</a></footer></article></div>}
  </div>;
}

