import { Download, Moon, RotateCcw, ShieldCheck, Sun, Type, X } from 'lucide-react';
import { useState } from 'react';
import { PageHeader } from '../components/ui';
import { useLearning } from '../context/LearningContext';

export default function SettingsPage() {
  const { state, updateSettings, exportProgress, resetProgress } = useLearning();
  const [confirmReset, setConfirmReset] = useState(false);
  return <div><PageHeader eyebrow="SETTINGS" title="Make the study space yours." description="Your preferences and progress stay in this browser by default. No learner account or paid service is required." />
    <div className="settings-layout"><section className="settings-section"><div><span><Sun /></span><div><h2>Appearance</h2><p>Choose a theme and reading size.</p></div></div><label>Theme<div className="setting-options">{(['light', 'dark', 'system'] as const).map((item) => <button className={state.theme === item ? 'is-active' : ''} onClick={() => updateSettings({ theme: item })} key={item}>{item === 'light' ? <Sun /> : item === 'dark' ? <Moon /> : <Type />}{item}</button>)}</div></label><label>Text size<input type="range" min="0.9" max="1.2" step="0.05" value={state.fontScale} onChange={(event) => updateSettings({ fontScale: Number(event.target.value) })} /><strong>{Math.round(state.fontScale * 100)}%</strong></label><label className="toggle-row"><span><strong>High contrast</strong><small>Increase borders and foreground contrast.</small></span><input type="checkbox" checked={state.highContrast} onChange={(event) => updateSettings({ highContrast: event.target.checked })} /></label><label className="toggle-row"><span><strong>Reduce motion</strong><small>Limit flips, orbits, and decorative animation.</small></span><input type="checkbox" checked={state.reducedMotion} onChange={(event) => updateSettings({ reducedMotion: event.target.checked })} /></label></section>
      <section className="settings-section"><div><span><Type /></span><div><h2>Learner goals</h2><p>Used for dashboard and planner feedback.</p></div></div><label>Display name<input value={state.learnerName} onChange={(event) => updateSettings({ learnerName: event.target.value.slice(0, 30) })} /></label><label>Daily study goal<input type="number" min="10" max="240" value={state.dailyGoalMinutes} onChange={(event) => updateSettings({ dailyGoalMinutes: Number(event.target.value) })} /><strong>minutes</strong></label><label>Target score<input type="number" min="50" max="100" value={state.targetScore} onChange={(event) => updateSettings({ targetScore: Number(event.target.value) })} /><strong>%</strong></label></section>
      <section className="settings-section"><div><span><ShieldCheck /></span><div><h2>Data and privacy</h2><p>Stored locally under one versioned browser key.</p></div></div><div className="data-actions"><button className="button button--secondary" onClick={exportProgress}><Download /> Export progress JSON</button><button className="button button--danger" onClick={() => setConfirmReset(true)}><RotateCcw /> Reset local progress</button></div><div className="source-box"><strong>No cloud account by default</strong><p>Notes, bookmarks, answers, flashcard scheduling, and plans are stored in localStorage. Clearing browser site data removes them unless exported first.</p></div></section></div>
    {confirmReset && <div className="dialog-backdrop" role="presentation"><section className="note-dialog" role="alertdialog" aria-modal="true" aria-label="Confirm progress reset"><div className="panel__head"><div><span className="eyebrow">PERMANENT LOCAL RESET</span><h2>Erase this browser’s learning data?</h2></div><button className="icon-button" onClick={() => setConfirmReset(false)} aria-label="Cancel reset"><X /></button></div><p>This removes completed lessons, notes, bookmarks, question history, card reviews, and study plans on this device. Export first if you want a backup.</p><div className="note-dialog__actions"><button className="button button--secondary" onClick={() => setConfirmReset(false)}>Cancel</button><button className="button button--danger" onClick={() => { resetProgress(); setConfirmReset(false); }}>Yes, reset progress</button></div></section></div>}
  </div>;
}

