import type { PracticeQuestion } from './types';

const base = {
  lessonId: '2026-nclex-pn-clinical-judgment-prioritization',
  subject: 'NCLEX Preparation',
  difficulty: 'hard' as const,
  clientNeeds: 'Integrated Processes: Clinical Judgment',
};

export const complexQuestions: PracticeQuestion[] = [
  {
    ...base,
    id: 'complex-001',
    type: 'ordered-response',
    prompt: 'Place the clinical judgment actions in the best sequence for a newly reported change in condition.',
    options: ['Evaluate the response', 'Recognize and validate cues', 'Take the selected action', 'Prioritize likely explanations', 'Generate safe options'],
    correct: [],
    orderedItems: ['Evaluate the response', 'Recognize and validate cues', 'Take the selected action', 'Prioritize likely explanations', 'Generate safe options'],
    correctOrder: [1, 3, 4, 2, 0],
    rationale: 'A safe sequence recognizes cues, analyzes/prioritizes them, generates options, acts, and evaluates the outcome.',
    optionRationales: [],
    priorityConcept: 'Clinical judgment cycle',
    testTakingClue: 'Start with data and end with evaluation.',
  },
  {
    ...base,
    id: 'complex-002',
    type: 'matching',
    prompt: 'Match each transmission category with its core environmental or PPE concept.',
    options: [], correct: [],
    matchingPairs: [
      { left: 'Contact', right: 'Gown/gloves and dedicated or disinfected equipment as directed' },
      { left: 'Droplet', right: 'Medical mask for close respiratory exposure as directed' },
      { left: 'Airborne', right: 'Fit-tested respirator and airborne isolation room as directed' },
      { left: 'Standard', right: 'Risk-based precautions for every client' },
    ],
    rationale: 'Standard Precautions apply to every client; transmission-based precautions add contact, droplet, or airborne controls.',
    optionRationales: [],
    priorityConcept: 'Transmission prevention',
    testTakingClue: 'Match the route of spread to the barrier or room control.',
    clientNeeds: 'Safe and Effective Care Environment: Safety and Infection Control',
  },
  {
    ...base,
    id: 'complex-003',
    lessonId: 'dosage-calculation-foundations-safe-rounding',
    subject: 'Dosage Calculations',
    type: 'dosage',
    prompt: 'An order is 375 mg. The available liquid contains 250 mg in 5 mL. Enter the volume in mL.',
    options: [], correct: [7.5],
    rationale: 'Desired/have x quantity = 375/250 x 5 = 7.5 mL.',
    optionRationales: [],
    priorityConcept: 'Desired over have',
    testTakingClue: 'Keep mg aligned, then confirm the answer is in mL.',
    clientNeeds: 'Physiological Integrity: Pharmacological Therapies',
  },
  {
    ...base,
    id: 'complex-004',
    type: 'matrix',
    prompt: 'For each task, select whether it is generally appropriate to delegate to trained assistive personnel or retain with the licensed nurse. Verify local scope and policy.',
    options: [], correct: [],
    matrixRows: [
      { label: 'Obtain routine vital signs for a stable client', options: ['Delegate', 'Retain'], correct: 0 },
      { label: 'Interpret a new change in respiratory status', options: ['Delegate', 'Retain'], correct: 1 },
      { label: 'Assist a stable client with an established ambulation plan', options: ['Delegate', 'Retain'], correct: 0 },
      { label: 'Provide initial teaching for a new medication', options: ['Delegate', 'Retain'], correct: 1 },
    ],
    rationale: 'Predictable routine tasks may be delegated when the person is trained and the client is stable; assessment, judgment, initial teaching, and evaluation are retained.',
    optionRationales: [],
    priorityConcept: 'Five rights of delegation',
    testTakingClue: 'Separate task completion from nursing judgment.',
    clientNeeds: 'Safe and Effective Care Environment: Coordinated Care',
  },
  {
    ...base,
    id: 'complex-005',
    lessonId: 'adult-19-shock-sepsis',
    subject: 'Adult Health',
    type: 'bow-tie',
    prompt: 'A client with suspected infection becomes confused, tachypneic, cool, and hypotensive. Choose the most likely condition, two first nursing actions, and two parameters to monitor.',
    options: [], correct: [],
    bowTie: {
      conditions: ['Stable localized infection', 'Sepsis with impaired perfusion', 'Simple anxiety'],
      actions: ['Activate urgent evaluation/response per protocol', 'Perform focused ABC/perfusion assessment', 'Delay until the next routine round', 'Offer food before assessment'],
      parameters: ['Mental status and blood pressure trend', 'Respiratory status and oxygenation', 'Hair color', 'Remote childhood history'],
      correctCondition: 1,
      correctActions: [0, 1],
      correctParameters: [0, 1],
    },
    rationale: 'Infection plus acute organ/perfusion cues suggests sepsis. Immediate assessment and escalation with close respiratory, neurologic, and circulatory monitoring are priorities.',
    optionRationales: [],
    priorityConcept: 'Time-sensitive deterioration',
    testTakingClue: 'Cluster the new findings instead of explaining each one separately.',
    clientNeeds: 'Physiological Integrity: Reduction of Risk Potential',
  },
  {
    ...base,
    id: 'complex-006',
    lessonId: 'foundations-documentation-sbar',
    subject: 'Nursing Foundations',
    type: 'highlight',
    prompt: 'Highlight the words that are subjective client-reported data.',
    options: [], correct: [],
    highlightText: 'Client states, “I feel dizzy when I stand.” Blood pressure is 98/60 mm Hg while seated. Skin is warm and dry. Assisted back to bed.',
    highlightAnswers: ['I feel dizzy when I stand.'],
    rationale: 'The client’s own statement is subjective data. Measured blood pressure, observed skin, and the nursing action are objective or action data.',
    optionRationales: [],
    priorityConcept: 'Objective documentation',
    testTakingClue: 'Subjective data come from what the client reports.',
    clientNeeds: 'Safe and Effective Care Environment: Coordinated Care',
  },
  {
    ...base,
    id: 'complex-007',
    lessonId: 'foundations-medication-administration-safety',
    subject: 'Nursing Foundations',
    type: 'ordered-response',
    prompt: 'Order these medication-administration checkpoints from preparation through follow-up.',
    options: ['Evaluate response', 'Verify order/allergies/relevant data', 'Identify client and explain', 'Prepare and compare label', 'Administer and document'],
    correct: [], orderedItems: ['Evaluate response', 'Verify order/allergies/relevant data', 'Identify client and explain', 'Prepare and compare label', 'Administer and document'],
    correctOrder: [1, 3, 2, 4, 0],
    rationale: 'Safe administration begins with verification and preparation, proceeds to bedside identification and administration, and ends with evaluation.',
    optionRationales: [],
    priorityConcept: 'Medication-use process',
    testTakingClue: 'Evaluation cannot occur before the medication is given.',
    clientNeeds: 'Physiological Integrity: Pharmacological Therapies',
  },
  {
    ...base,
    id: 'complex-008',
    lessonId: 'adult-15-fluids-electrolytes',
    subject: 'Adult Health',
    type: 'matching',
    prompt: 'Match each finding cluster with the electrolyte concern it most strongly suggests. These clues require laboratory confirmation.',
    options: [], correct: [],
    matchingPairs: [
      { left: 'New weakness plus rhythm change', right: 'Potassium imbalance' },
      { left: 'Headache, confusion, or seizure with fluid shift', right: 'Sodium imbalance' },
      { left: 'Tingling and muscle spasm', right: 'Low calcium or magnesium' },
      { left: 'Reduced reflexes and respiratory slowing', right: 'High magnesium concern' },
    ],
    rationale: 'Electrolyte disorders form recognizable clusters, but symptoms overlap and require assessment, laboratory confirmation, and escalation.',
    optionRationales: [],
    priorityConcept: 'Pattern recognition',
    testTakingClue: 'Connect potassium with electrical activity and sodium with neurologic fluid shifts.',
    clientNeeds: 'Physiological Integrity: Reduction of Risk Potential',
  },
  {
    ...base,
    id: 'complex-009',
    lessonId: 'maternal-newborn-priorities',
    subject: 'Maternal and Newborn Nursing',
    type: 'matrix',
    prompt: 'Classify each postpartum finding as expected monitoring or urgent escalation.',
    options: [], correct: [],
    matrixRows: [
      { label: 'Small amount of expected lochia with firm midline uterus', options: ['Monitor', 'Urgent escalation'], correct: 0 },
      { label: 'Heavy bleeding with dizziness and tachycardia', options: ['Monitor', 'Urgent escalation'], correct: 1 },
      { label: 'Mild afterpains during feeding with otherwise stable findings', options: ['Monitor', 'Urgent escalation'], correct: 0 },
      { label: 'New severe headache with vision changes', options: ['Monitor', 'Urgent escalation'], correct: 1 },
    ],
    rationale: 'Heavy bleeding with perfusion changes and severe neurologic symptoms are time-sensitive postpartum warnings.',
    optionRationales: [],
    priorityConcept: 'Postpartum warning signs',
    testTakingClue: 'Pair the amount or symptom with evidence of instability.',
    clientNeeds: 'Health Promotion and Maintenance',
  },
  {
    ...base,
    id: 'complex-010',
    lessonId: 'adult-13-diabetes-insulin-safety',
    subject: 'Adult Health',
    type: 'bow-tie',
    prompt: 'A client receiving glucose-lowering therapy is sweaty, shaky, and confused. Choose the likely condition, two immediate actions, and two monitoring priorities.',
    options: [], correct: [],
    bowTie: {
      conditions: ['Hypoglycemia', 'Hypernatremia', 'Stable expected response'],
      actions: ['Check glucose promptly if this does not delay care', 'Follow the approved hypoglycemia protocol and escalate based on consciousness', 'Give the next glucose-lowering dose now', 'Encourage the client to walk alone'],
      parameters: ['Level of consciousness and airway safety', 'Repeat glucose and symptom response', 'Shoe size', 'Remote immunization date'],
      correctCondition: 0,
      correctActions: [0, 1],
      correctParameters: [0, 1],
    },
    rationale: 'Adrenergic and neuroglycopenic symptoms suggest hypoglycemia. Rapid confirmation when feasible, protocol-based treatment, and reassessment are priorities.',
    optionRationales: [],
    priorityConcept: 'Hypoglycemia safety',
    testTakingClue: 'Sweating plus behavior change in a treated client is an urgent low-glucose pattern.',
    clientNeeds: 'Physiological Integrity: Pharmacological Therapies',
  },
];
