import type { DosageProblem } from './types';

export const dosageProblems: DosageProblem[] = [
  {
    id: 'dose-001', title: 'Tablets from a scored strength', category: 'Tablets', difficulty: 'easy',
    prompt: 'The order is 500 mg. Tablets available contain 250 mg each. How many tablets are needed?',
    ordered: '500 mg', available: '250 mg/tablet', answer: 2, unit: 'tablets', tolerance: 0,
    formula: 'Desired / Have x Quantity',
    steps: ['Match the ordered and available units: both are mg.', 'Divide 500 by 250.', 'Multiply by 1 tablet.', 'Confirm that 2 tablets provide 500 mg.'],
    safetyNote: 'Confirm the tablet may be split only when a split dose is required and the product is approved for splitting.',
  },
  {
    id: 'dose-002', title: 'Half-tablet dose', category: 'Tablets', difficulty: 'easy',
    prompt: 'The order is 25 mg. Tablets available contain 50 mg each. How many tablets are needed?',
    ordered: '25 mg', available: '50 mg/tablet', answer: 0.5, unit: 'tablet', tolerance: 0,
    formula: 'Desired / Have x Quantity',
    steps: ['Units already match.', 'Divide 25 by 50.', 'The result is 0.5 tablet.', 'Check the medication is scored and splitting is permitted.'],
    safetyNote: 'Never assume a tablet can be split; verify the formulation and policy.',
  },
  {
    id: 'dose-003', title: 'Liquid medication volume', category: 'Liquids', difficulty: 'easy',
    prompt: 'The order is 300 mg. The label reads 150 mg per 5 mL. How many mL are needed?',
    ordered: '300 mg', available: '150 mg/5 mL', answer: 10, unit: 'mL', tolerance: 0.05,
    formula: 'Desired / Have x Quantity',
    steps: ['Divide 300 mg by 150 mg.', 'Multiply the result by 5 mL.', '2 x 5 mL = 10 mL.', 'Use an appropriate oral measuring device.'],
    safetyNote: 'Read the concentration on the exact container; concentrations can differ.',
  },
  {
    id: 'dose-004', title: 'Small liquid volume', category: 'Liquids', difficulty: 'medium',
    prompt: 'The order is 75 mg. The medication is available as 100 mg per 2 mL. How many mL are needed?',
    ordered: '75 mg', available: '100 mg/2 mL', answer: 1.5, unit: 'mL', tolerance: 0.05,
    formula: 'Desired / Have x Quantity',
    steps: ['Units match in mg.', '75 / 100 = 0.75.', '0.75 x 2 mL = 1.5 mL.', 'Recheck the decimal placement.'],
    safetyNote: 'Use a device that can accurately measure the calculated volume.',
  },
  {
    id: 'dose-005', title: 'Grams to milligrams', category: 'Conversions', difficulty: 'easy',
    prompt: 'Convert 1.25 g to milligrams.', ordered: '1.25 g', available: '1 g = 1,000 mg',
    answer: 1250, unit: 'mg', tolerance: 0,
    formula: 'grams x 1,000 = milligrams',
    steps: ['Write the conversion factor: 1 g = 1,000 mg.', 'Multiply 1.25 by 1,000.', 'Move the decimal three places right.', 'The result is 1,250 mg.'],
    safetyNote: 'Keep a leading zero for values below 1 and never use a trailing zero.',
  },
  {
    id: 'dose-006', title: 'Milligrams to micrograms', category: 'Conversions', difficulty: 'medium',
    prompt: 'Convert 0.4 mg to micrograms.', ordered: '0.4 mg', available: '1 mg = 1,000 mcg',
    answer: 400, unit: 'mcg', tolerance: 0,
    formula: 'milligrams x 1,000 = micrograms',
    steps: ['Use 1 mg = 1,000 mcg.', 'Multiply 0.4 by 1,000.', 'The result is 400 mcg.', 'Check that mcg, not mg, is requested.'],
    safetyNote: 'Write micrograms as mcg; avoid the error-prone symbol µg in medication communication.',
  },
  {
    id: 'dose-007', title: 'Kilograms from pounds', category: 'Weight based', difficulty: 'easy',
    prompt: 'A client weighs 176 lb. What is the weight in kilograms?', ordered: '176 lb', available: '2.2 lb = 1 kg',
    answer: 80, unit: 'kg', tolerance: 0.05,
    formula: 'pounds / 2.2 = kilograms',
    steps: ['Divide pounds by 2.2.', '176 / 2.2 = 80.', 'Record 80 kg.', 'Use the measured current weight when available.'],
    safetyNote: 'Weight-based orders should use the weight and unit specified by policy and the order.',
  },
  {
    id: 'dose-008', title: 'Weight-based daily dose', category: 'Weight based', difficulty: 'medium',
    prompt: 'An order is 12 mg/kg/day for a client weighing 25 kg. What total amount is ordered each day?',
    ordered: '12 mg/kg/day', available: '25 kg', answer: 300, unit: 'mg/day', tolerance: 0.05,
    formula: 'mg/kg/day x kg = mg/day',
    steps: ['Confirm the weight is already in kg.', 'Multiply 12 mg by 25 kg.', 'Cancel kg units.', 'The total is 300 mg/day.'],
    safetyNote: 'Do not divide into doses unless the order states the number or frequency of divided doses.',
  },
  {
    id: 'dose-009', title: 'Divided weight-based dose', category: 'Weight based', difficulty: 'hard',
    prompt: 'An order is 30 mg/kg/day divided into 3 equal doses for a 24 kg client. How many mg are in each dose?',
    ordered: '30 mg/kg/day divided x3', available: '24 kg', answer: 240, unit: 'mg/dose', tolerance: 0.05,
    formula: '(mg/kg/day x kg) / doses per day',
    steps: ['30 x 24 = 720 mg/day.', 'The order says 3 equal doses.', '720 / 3 = 240.', 'Each dose is 240 mg.'],
    safetyNote: 'Compare the calculated single dose and daily dose with the safe range before administration.',
  },
  {
    id: 'dose-010', title: 'Safe daily range - lower limit', category: 'Safe dose range', difficulty: 'medium',
    prompt: 'A safe range is 10 to 15 mg/kg/day for a 20 kg client. What is the minimum safe total daily dose?',
    ordered: '10-15 mg/kg/day', available: '20 kg', answer: 200, unit: 'mg/day', tolerance: 0.05,
    formula: 'lower mg/kg/day x kg',
    steps: ['Use the lower boundary: 10 mg/kg/day.', 'Multiply 10 by 20 kg.', 'The minimum is 200 mg/day.', 'Calculate the upper boundary separately.'],
    safetyNote: 'A safe-range calculation does not replace checking allergies, contraindications, concentration, and the actual order.',
  },
  {
    id: 'dose-011', title: 'Safe daily range - upper limit', category: 'Safe dose range', difficulty: 'medium',
    prompt: 'A safe range is 10 to 15 mg/kg/day for a 20 kg client. What is the maximum safe total daily dose?',
    ordered: '10-15 mg/kg/day', available: '20 kg', answer: 300, unit: 'mg/day', tolerance: 0.05,
    formula: 'upper mg/kg/day x kg',
    steps: ['Use the upper boundary: 15 mg/kg/day.', 'Multiply 15 by 20 kg.', 'The maximum is 300 mg/day.', 'The safe daily range is 200 to 300 mg/day.'],
    safetyNote: 'Clarify an order that falls outside the verified safe range before giving it.',
  },
  {
    id: 'dose-012', title: 'IV pump rate', category: 'IV rates', difficulty: 'easy',
    prompt: 'Infuse 1,000 mL over 8 hours. What pump rate is needed?', ordered: '1,000 mL over 8 hr', available: 'electronic pump',
    answer: 125, unit: 'mL/hr', tolerance: 0.05,
    formula: 'total volume / hours',
    steps: ['Divide 1,000 mL by 8 hours.', '1,000 / 8 = 125.', 'Set 125 mL/hr.', 'Confirm the total volume and time.'],
    safetyNote: 'Trace the line and verify pump settings according to policy.',
  },
  {
    id: 'dose-013', title: 'IV pump rate with minutes', category: 'IV rates', difficulty: 'medium',
    prompt: 'Infuse 150 mL over 45 minutes. What pump rate in mL/hr is needed?', ordered: '150 mL over 45 min', available: 'electronic pump',
    answer: 200, unit: 'mL/hr', tolerance: 0.05,
    formula: 'volume / hours',
    steps: ['Convert 45 minutes to 0.75 hour.', 'Divide 150 by 0.75.', 'The rate is 200 mL/hr.', 'Verify the pump displays mL/hr.'],
    safetyNote: 'Convert minutes to hours before calculating an hourly rate.',
  },
  {
    id: 'dose-014', title: 'Gravity infusion', category: 'IV rates', difficulty: 'medium',
    prompt: 'Infuse 500 mL over 4 hours using tubing calibrated at 15 gtt/mL. What drip rate is needed?',
    ordered: '500 mL over 4 hr', available: '15 gtt/mL', answer: 31, unit: 'gtt/min', tolerance: 0,
    formula: '(mL x drop factor) / minutes',
    steps: ['Convert 4 hours to 240 minutes.', '500 x 15 = 7,500 gtt.', '7,500 / 240 = 31.25.', 'Round drops to 31 gtt/min.'],
    safetyNote: 'Gravity drops are counted as whole drops; follow the required rounding rule.',
  },
  {
    id: 'dose-015', title: 'Microdrip rate', category: 'IV rates', difficulty: 'medium',
    prompt: 'Infuse 120 mL over 2 hours with microdrip tubing at 60 gtt/mL. What is the drip rate?',
    ordered: '120 mL over 2 hr', available: '60 gtt/mL', answer: 60, unit: 'gtt/min', tolerance: 0,
    formula: '(mL x 60 gtt/mL) / minutes',
    steps: ['Convert 2 hours to 120 minutes.', '120 x 60 = 7,200 gtt.', '7,200 / 120 = 60.', 'Set 60 gtt/min.'],
    safetyNote: 'Confirm the drop factor printed on the tubing package.',
  },
  {
    id: 'dose-016', title: 'Infusion completion time', category: 'IV rates', difficulty: 'easy',
    prompt: 'A 600 mL bag infuses at 150 mL/hr. How many hours will it take?', ordered: '600 mL', available: '150 mL/hr',
    answer: 4, unit: 'hr', tolerance: 0.05,
    formula: 'volume / rate',
    steps: ['Divide 600 mL by 150 mL/hr.', 'The mL units cancel.', 'The result is 4 hours.', 'Add 4 hours to the start time if a clock time is requested.'],
    safetyNote: 'Account for clinical interruptions only when documenting the actual completion time.',
  },
  {
    id: 'dose-017', title: 'Intake total', category: 'Intake and output', difficulty: 'easy',
    prompt: 'A client drinks 8 oz juice, 120 mL water, and 6 oz soup. What is the total intake in mL?',
    ordered: '8 oz + 120 mL + 6 oz', available: '1 oz = 30 mL', answer: 540, unit: 'mL', tolerance: 0,
    formula: 'ounces x 30 + known milliliters',
    steps: ['8 oz x 30 = 240 mL.', '6 oz x 30 = 180 mL.', 'Add 240 + 120 + 180.', 'Total intake is 540 mL.'],
    safetyNote: 'Count items that are liquid at room temperature according to course/facility rules.',
  },
  {
    id: 'dose-018', title: 'Reconstitution concentration', category: 'Reconstitution', difficulty: 'medium',
    prompt: 'After reconstitution, a vial contains 500 mg in 4 mL. What volume contains a 375 mg dose?',
    ordered: '375 mg', available: '500 mg/4 mL', answer: 3, unit: 'mL', tolerance: 0.05,
    formula: 'Desired / Have x Quantity',
    steps: ['Use the final concentration on the reconstituted label.', '375 / 500 = 0.75.', '0.75 x 4 mL = 3 mL.', 'Label the vial per policy if any remains.'],
    safetyNote: 'Use the manufacturer-specified diluent and final concentration; do not infer them.',
  },
  {
    id: 'dose-019', title: 'Units per mL', category: 'Insulin concepts', difficulty: 'easy',
    prompt: 'A solution contains 100 units per mL. What volume contains 25 units?', ordered: '25 units', available: '100 units/mL',
    answer: 0.25, unit: 'mL', tolerance: 0.005,
    formula: 'Desired units / units per mL',
    steps: ['Divide 25 units by 100 units/mL.', 'The result is 0.25 mL.', 'Confirm the intended product and delivery device.', 'Use independent checks when required.'],
    safetyNote: 'Insulin is high-alert. Use the correct insulin syringe/device and follow independent-check policy.',
  },
  {
    id: 'dose-020', title: 'Units per hour', category: 'High-alert infusions', difficulty: 'hard',
    prompt: 'A prepared infusion contains 25,000 units in 500 mL and runs at 20 mL/hr. How many units per hour are delivered?',
    ordered: '20 mL/hr', available: '25,000 units/500 mL', answer: 1000, unit: 'units/hr', tolerance: 0.05,
    formula: '(total units / total mL) x mL/hr',
    steps: ['25,000 / 500 = 50 units/mL.', '50 units/mL x 20 mL/hr = 1,000 units/hr.', 'Cancel mL.', 'Compare with the order and smart-pump library.'],
    safetyNote: 'This is calculation practice only. High-alert infusions require protocol, pump-library, and independent verification.',
  },
  {
    id: 'dose-021', title: 'mL per hour from units', category: 'High-alert infusions', difficulty: 'hard',
    prompt: 'A prepared infusion contains 20,000 units in 500 mL. The order is 800 units/hr. What rate in mL/hr is needed?',
    ordered: '800 units/hr', available: '20,000 units/500 mL', answer: 20, unit: 'mL/hr', tolerance: 0.05,
    formula: 'ordered units/hr / concentration units/mL',
    steps: ['20,000 / 500 = 40 units/mL.', '800 units/hr / 40 units/mL = 20 mL/hr.', 'Cancel units.', 'Verify the standard concentration.'],
    safetyNote: 'Never bypass a required high-alert double check.',
  },
  {
    id: 'dose-022', title: 'Dose by body surface schedule', category: 'Divided doses', difficulty: 'medium',
    prompt: 'A total daily dose is 900 mg and is ordered in 3 equal doses. How many mg are given per dose?',
    ordered: '900 mg/day divided x3', available: '3 doses/day', answer: 300, unit: 'mg/dose', tolerance: 0,
    formula: 'daily dose / doses per day',
    steps: ['Identify the total daily amount: 900 mg.', 'Identify 3 equal doses.', '900 / 3 = 300.', 'Each dose is 300 mg.'],
    safetyNote: 'Confirm that “three doses” and “every 8 hours” are interpreted according to the actual order and schedule.',
  },
  {
    id: 'dose-023', title: 'Rate by kilograms per minute', category: 'Weight based', difficulty: 'hard',
    prompt: 'An educational order is 5 mcg/kg/min for a 60 kg client. How many mcg per minute is that?',
    ordered: '5 mcg/kg/min', available: '60 kg', answer: 300, unit: 'mcg/min', tolerance: 0.05,
    formula: 'mcg/kg/min x kg',
    steps: ['Multiply 5 mcg/kg/min by 60 kg.', 'Cancel kg.', 'The result is 300 mcg/min.', 'A separate concentration calculation would be needed for mL/hr.'],
    safetyNote: 'Do not convert to a pump setting without the verified bag concentration and protocol.',
  },
  {
    id: 'dose-024', title: 'Rounding to a tenth', category: 'Rounding', difficulty: 'easy',
    prompt: 'Round 2.46 mL to the nearest tenth.', ordered: '2.46 mL', available: 'nearest tenth', answer: 2.5, unit: 'mL', tolerance: 0,
    formula: 'inspect the hundredths digit',
    steps: ['The tenths digit is 4.', 'The hundredths digit is 6.', 'Because 6 is 5 or more, round the tenths up.', 'The result is 2.5 mL.'],
    safetyNote: 'Use the precision requested by the problem, medication, measuring device, and policy.',
  },
  {
    id: 'dose-025', title: 'Leading-zero safety', category: 'Rounding', difficulty: 'easy',
    prompt: 'Enter the safe numeric form of a dose calculated as five tenths of a milliliter.',
    ordered: 'five tenths mL', available: 'safe notation', answer: 0.5, unit: 'mL', tolerance: 0,
    formula: 'leading zero for values below 1',
    steps: ['The numeric value is 0.5.', 'Place a zero before the decimal.', 'Do not add a trailing zero.', 'Write 0.5 mL.'],
    safetyNote: 'A naked decimal (.5) can be misread as 5; a trailing zero (5.0) can be misread as 50.',
  },
];

